### ISSUE TITLE
DB Issue on startup

### ISSUE THREAD

**Issue by lumberj** [interledger/five-bells-ledger#101]
```
five-bells-ledger » LEDGER_DB_URI=sqlite://:memory: node app.js
2016-01-13T21:47:34.959Z expiry monitor DEBUG checking for transfers to expire
2016-01-13T21:47:34.976Z db DEBUG Executing (default): PRAGMA busy_timeout = 0;
2016-01-13T21:47:34.981Z db DEBUG Executing (default): PRAGMA journal_mode = WAL;
2016-01-13T21:47:34.982Z db DEBUG Executing (default): PRAGMA synchronous = off;
2016-01-13T21:47:34.989Z db DEBUG Executing (default): SELECT `primary`, `name`, `balance`, `connector`, `password`, `public_key`, `is_admin`, `created_at`, `updated_at` FROM `Accounts` AS `Account` WHERE `Account`.`name` = 'hold' LIMIT 1;
2016-01-13T21:47:34.993Z app CRIT SequelizeDatabaseError: SQLITE_ERROR: no such table: Accounts
    at Query.formatError (/Users/alan/Projects/bundle/node_modules/five-bells-ledger/node_modules/sequelize/lib/dialects/sqlite/query.js:328:14)
    at afterExecute (/Users/alan/Projects/bundle/node_modules/five-bells-ledger/node_modules/sequelize/lib/dialects/sqlite/query.js:100:29)
    at replacement (/Users/alan/Projects/bundle/node_modules/five-bells-ledger/node_modules/sqlite3/lib/trace.js:20:31)
    at Statement.errBack (/Users/alan/Projects/bundle/node_modules/five-bells-ledger/node_modules/sqlite3/lib/sqlite3.js:16:21)
2016-01-13T21:47:35.982Z db DEBUG Executing (default): SELECT `id`, `subscription_id`, `transfer_id`, `retry_count`, `retry_at`, `created_at`, `updated_at` FROM `Notifications` AS `Notification` WHERE (`Notification`.`retry_at` IS NULL OR `Notification`.`retry_at` < '2016-01-13 21:47:35.976 +00:00');
```

**Comment by sentientwaffle** [comment]
It doesn't create the tables automatically.. use `LEDGER_DB_SYNC=1` if you want to make it.
