### ISSUE TITLE
Deadlock detected on PUT /fulfillment (postgres)

### ISSUE THREAD

**Issue by vhpoet** [interledger/five-bells-ledger#323]
{  
   "name":"ledger",
   "hostname":"vahe-2.local",
   "pid":18512,
   "module":"error-handler",
   "level":50,
   "err":{  
      "message":"insert into \"L_ENTRIES\" (\"ACCOUNT_ID\", \"TRANSFER_ID\") values ($1, $2) - deadlock detected",
      "name":"error",
      "stack":"error: deadlock detected\n    at Connection.parseE (/Users/vh/localhost/ripple/five-bells-wallet/node_modules/pg/lib/connection.js:539:11)\n    at Connection.parseMessage (/Users/vh/localhost/ripple/five-bells-wallet/node_modules/pg/lib/connection.js:366:17)\n    at Socket.<anonymous> (/Users/vh/localhost/ripple/five-bells-wallet/node_modules/pg/lib/connection.js:105:22)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:177:18)\n    at Socket.Readable.push (_stream_readable.js:135:10)\n    at TCP.onread (net.js:542:20)\nFrom previous event:\n    at Client._query (/Users/vh/localhost/ripple/five-bells-wallet/node_modules/knex/lib/dialects/postgres/index.js:150:12)\n    at Client.query (/Users/vh/localhost/ripple/five-bells-wallet/node_modules/knex/lib/client.js:136:24)\n    at /Users/vh/localhost/ripple/five-bells-wallet/node_modules/knex/lib/transaction.js:225:21\nFrom previous event:\n    at Client.trxClient.query (/Users/vh/localhost/ripple/five-bells-wallet/node_modules/knex/lib/transaction.js:222:26)\n    at Runner.<anonymous> (/Users/vh/localhost/ripple/five-bells-wallet/node_modules/knex/lib/runner.js:115:24)\nFrom previous event:\n    at /Users/vh/localhost/ripple/five-bells-wallet/node_modules/knex/lib/runner.js:43:21\nFrom previous event:\n    at Runner.run (/Users/vh/localhost/ripple/five-bells-wallet/node_modules/knex/lib/runner.js:29:20)\n    at QueryBuilder.Target.then (/Users/vh/localhost/ripple/five-bells-wallet/node_modules/knex/lib/interface.js:26:43)\n    at runCallback (timers.js:566:20)\n    at tryOnImmediate (timers.js:546:5)\n    at processImmediate [as _immediateCallback] (timers.js:525:5)",
      "code":"40P01"
   },
   "msg":"insert into \"L_ENTRIES\" (\"ACCOUNT_ID\", \"TRANSFER_ID\") values ($1, $2) - deadlock detected",
   "time":"2016-09-12T21:19:33.133Z",
   "v":0
}

**Comment by justmoon** [comment]
I believe this might have been fixed with https://github.com/interledgerjs/five-bells-ledger/commit/4a8ed1c0245a83921366b691c28d231621a12621

Any way to confirm?

**Comment by vhpoet** [comment]
@justmoon It might've been caused by 200tps stress test, will try to test it today.
